import localFont from "next/font/local";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";

import { ThemeProvider } from "@/context/ThemeContext";

import "./globals.css";


const geistMono = localFont({
	variable: "--font-geist-mono",
	src: "./fonts/GeistMonoVF.woff",
	weight: "100 900",
});

const geistSans = localFont({
	variable: "--font-geist-sans",
	src: "./fonts/GeistVF.woff",
	weight: "100 900",
});

export const metadata = {
	title: "Gerald Llyod",
	description: "Generated by Gerald Llyod",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider>
					<div className="container">
						<Navbar />
						{children}
						<Footer />
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
